services:
  mapillary_worker:
    build:
      context: ..
      dockerfile: docker/Dockerfile.worker
    working_dir: /app
    volumes:
      - ../config:/app/config:ro
      - ../output:/app/output
      - ../data/osm:/app/data/osm
      - ../data/mapillary:/app/data/mapillary
    mem_limit: 6g